### ISSUE TITLE
Swagger support requires full document parsing

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/deckardcain#14]
In order to detect if the given document is Swagger, we're now trying to parse the document in JSON at first, and then in YAML.
This may give us problem for large payloads, as this is a CPU intensive operation and we can't go async with it.

**Comment by JackuB** [comment]
I could transform both Swagger-YAML and Swagger-JSON detection to regex, which would allow us to drop YAML dependency resulting in smaller [browser build](https://trello.com/c/Tx5Bp0zX/32-create-browser-build-for-decard-cain).

Would you be okay with it guys?

**Comment by honzajavorek** [comment]
Sure! Deckard should be non-blocking heuristics, not parsing. See:

- https://github.com/apiaryio/deckardcain/pull/3#commitcomment-14411386
- https://github.com/apiaryio/deckardcain/pull/3#issuecomment-157009666

**Comment by JackuB** [comment]
Fixed in #16
